server:
  port: 8080   # HTTP (Tomcat) port
# Spring properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect